### ISSUE TITLE
Should this be a plugin or parser?

### ISSUE THREAD

**Issue by phated** [sullenor/postcss-modules-parser#4]
It seems that this module is called a parser but is actually a plugin.  Does it make more sense to turn it into a parser as documented at https://github.com/postcss/postcss/blob/master/docs/syntax.md#parser?  I'm wondering if you could avoid the `fetch` option if it was a true parser for postcss.

**Comment by mightyaleksey** [comment]
Hi, that's a good question. I think, when I created it, I didn't know about custom parsers and I need to look the documentation to understand it better.

Anyways, I agree with you that it's not a good name for the plugin and in my opinion it should be two separated modules: parser and tokenizer (stringifier, cause in some cause you do need only JSON object with tokens, not CSS).

Anyways, thank you for the tip :) I'll try to make a small research in that area.
