### ISSUE TITLE
Rename to postcss-modules-icss

### ISSUE THREAD

**Issue by TrySound** [sullenor/postcss-modules-parser#6]
Would be cool to rename it to `postcss-modules-icss` to be more descriptive.
We can return tokens in messages.
/cc @sullenor @michael-ciniawsky

**Comment by mightyaleksey** [comment]
I actually would like to mark it deprecated and use [postcss-modules-resolve-imports](https://github.com/css-modules/postcss-modules-resolve-imports) instead where it's necessary.

**Comment by michael-ciniawsky** [comment]
@TrySound How would the token export like  ? 
@sullenor Coud it be deprecated instead then and is tolen export in `postcss-modules-resolve-import` possible ?

**Comment by mightyaleksey** [comment]
@michael-ciniawsky `postcss-modules-resolve-import` actually does export of tokens (locals or whatever they are). I attach them to the resulting ast object, so you may obtain them by accessing `result.root.exports`.

https://github.com/css-modules/postcss-modules-resolve-imports/blob/master/test/setup.js#L32-L38
https://github.com/css-modules/postcss-modules-resolve-imports/blob/master/lib/sync.js#L61

**Comment by mightyaleksey** [comment]
@michael-ciniawsky I still working on async interface for file loading. And I still I don't know how to integrate it to webpack css-loader, cause loaded files should be preprocess also by the remaining loaders also (the thing I tried to explain here: https://github.com/webpack-contrib/css-loader/pull/542#issuecomment-303934324).

**Comment by michael-ciniawsky** [comment]
`result.root.exports` => `result.messages.exports` or the like ? (it's recommended IPC for PostCSS Metadata)

e.g `result.messages` has `result.messages.dependencies` already supoorted by `postcss-import` && `postcss-url`

```js
postcss([ modules() ]).process(css, options)
  then((result) => {
     retunrn cb(null, result.css, result.map, { ast: result.root, messages: result.messages })
  })
``` 

But just to mention it for now, no bikeshed or opinions about it :), what works better in CSSM case

**Comment by michael-ciniawsky** [comment]
I'm not really sure how to handle CSS file loading/fetching atm, `composes` is one of the top issues in `css-loader` 😛

**Comment by michael-ciniawsky** [comment]
`css-modules-loader-core` (`postcss-modules`) has it's own file loader, but not really possible to use it in webpack I guess. Maybe one of these candidates `this.context/this.resolve/this.fs` [Loader API](https://webpack.js.org/api/loaders/) and an options to override the file loader 

```js
postcss( [ modules({ compose: { resolver: this.resolve || this.fs || ... } }) ]).process...
```

**Comment by mightyaleksey** [comment]
I see, actually I thought that `result#messages` is an array (according to the api http://api.postcss.org/Result.html), but JavaScript allows to assign any arbitrary props to it, so I can move it there.

**Comment by mightyaleksey** [comment]
Both `css-modules-loader-core` and `css-loader` have its custom file loader and `postcss-modules-parser` introduces another one for the `require-hook` :)
Supporting all of them can be time consuming :) Thats why I wanted to have one implementation :)

**Comment by michael-ciniawsky** [comment]
Yep it's just an array containing `{Object}` with e.g `{ type: 'modules', ...whatever }` :)

**Comment by mightyaleksey** [comment]
I'll check the API, may be it can help.

**Comment by mightyaleksey** [comment]
Oh, looks like I can't rename this repo :)
@geelen can you help me here? We would like to rename it to `postcss-modules-icss`.

**Comment by TrySound** [comment]
@sullenor Or maybe not :) Sokra added new convention looks more descriptive. `postcss-icss-url` etc. Maybe postcss-icss then? :)

**Comment by michael-ciniawsky** [comment]
`postcss-loader` will require a standalone ICSS plugin in 'global mode', so `postcss-icss` would be 👍 I think :)

**Comment by mightyaleksey** [comment]
Thanks
